name: Build Image

on:
  workflow_call:
    inputs:
      docker-file-path:
        description: 'Path to the Dockerfile'
        type: string
        required: false
        default: '.'
      runs-on:
        description: 'Runner to use'
        type: string
        required: false
        default: 'ubuntu-latest'

jobs:
  build-image:
    name: Build Image
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Docker Image
        working-directory: '${{ inputs.docker-file-path }}'
        run: |
          docker build -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/finhero-app:latest .
      
      - name: Push Docker Image
        working-directory: '${{ inputs.docker-file-path }}'
        run: |
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/finhero-app:latest