name: Build Image

on:
  workflow_call:
    inputs:
      docker-file-path:
        description: 'Path to the Dockerfile'
        type: string
        required: false
        default: '.'
      runs-on:
        description: 'Runner to use'
        type: string
        required: false
        default: 'ubuntu-latest'

jobs:
  build-image:
    name: Build Image
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run YAML to Github Output Action
        id: settings-parser
        uses: cristian-ci/action-yaml-github-output@v2
        with:
          file_path: './settings.yml'
      
      - name: SonarCloud Scan
        if: steps.settings-parser.outputs.sonarcloud_organization != '' && steps.settings-parser.outputs.sonarcloud_project_key != ''
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Docker Image
        working-directory: '${{ inputs.docker-file-path }}'
        run: |
          docker build -t ${{ steps.settings-parser.outputs.docker_registry }}/${{ steps.settings-parser.outputs.docker_name }}:${{ steps.settings-parser.outputs.docker_tag }} .
      
      - name: Push Docker Image
        working-directory: '${{ inputs.docker-file-path }}'
        run: |
          docker push ${{ steps.settings-parser.outputs.docker_registry }}/${{ steps.settings-parser.outputs.docker_name }}:${{ steps.settings-parser.outputs.docker_tag }}