name: Build Image

on:
  workflow_call:
    inputs:
      docker-file-path:
        description: 'Path to the Dockerfile'
        type: string
        required: false
        default: '.'
      runs-on:
        description: 'Runner to use'
        type: string
        required: false
        default: 'ubuntu-latest'

jobs:
  build-image:
    name: Build Image
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push Docker Image
        working-directory: '${{ inputs.docker-file-path }}'
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          SHORT_SHA=${IMAGE_TAG:0:7}
          IMAGE_NAME=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/finhero-app:$SHORT_SHA
          
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME docker.io/${{ secrets.DOCKERHUB_USERNAME }}/finhero-app:latest
          
          docker push $IMAGE_NAME
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/finhero-app:latest